# Generated by Django 6.0.4 on 2026-05-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_profilemodel_delete_taskmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prodect', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
